# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

first_term = 1
second_term = 2
curr_term = 0
sum_even_terms = 2 # second term (2) is even

while not curr_term > 4000000:
	curr_term = first_term + second_term

	first_term = second_term
	second_term = curr_term

	if curr_term % 2 == 0:
		sum_even_terms = sum_even_terms + curr_term

print(sum_even_terms)